services:
  api:
    env_file:
      - .env.prod
    ports:
      - "8002:8000"

  ui:
    env_file:
      - .env.prod
    ports:
      - "8503:8501"

  worker:
    env_file:
      - .env.prod

  redis:
    ports:
      - "6381:6379"
